### Add an employee using api gateway
POST http://localhost:8080/employee
Content-Type: application/json

{
  "id" : 1,
  "name" : "M. Oly Mahmud",
  "departmentId" : 1
}

### Get an employee using api-gateway
GET http://localhost:8080/employee/1
Content-Type: application/json


### Add a department using api-gateway
POST http://localhost:8080/department
Content-Type: application/json

{
  "departmentId": 1,
  "name": "Engineering"
}

### Get a department using api-gateway
GET http://localhost:8080/department/1
Content-Type: application/json




















### Add an employee
POST http://localhost:8081/employee
Content-Type: application/json

{
  "id" : 1,
  "name" : "M. Oly Mahmud",
  "departmentId" : 1
}

### Get an employee
GET http://localhost:8081/employee/1
Content-Type: application/json


### Add a department
POST http://localhost:8082/department
Content-Type: application/json

{
  "departmentId": 1,
  "name": "Engineering"
}

### Get a department
GET http://localhost:8082/department/1
Content-Type: application/json