server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: DEPARTMENT-SERVICE
            uri: lb://DEPARTMENT-SERVICE
            predicates:
              - Path=/department/**
          - id: EMPLOYEE-SERVICE
            uri: lb://EMPLOYEE-SERVICE
            predicates:
              - Path=/employee/**
