server:
  port: 8082
spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/department
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost