spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    password: mysecretpassword
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port:
    8081
eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka
  instance:
    hostname: localhost